### PR TITLE
Added looping over PlotStyle items for testing. Found some quirks.

### PR DESCRIPTION
**Pull request by prismv**
I wanted to add looping to obtain all png exports at once, and I found some 'quirks':

-  no direct setting of e.g. "retro" possible
-  unordered generation (using HashTable for styles) worked sometimes (!) for all styles
- orderer BTreeMap failed with all my tests with some latex error for Nature style
- 'Default' needs to be (alphabetically) first entry, otherwise Default has properties of previous style!

Hope this helps, although this could be seen as bad issue reporting style and not perfect example code extensions.

Sorry, if there are some stupid Rust errors. I'm beginner for Rust programming.

### CODE REVIEW

**Comment by Axect** [comment]
Hello, @prismv

Thank you for your contribution and for sharing your interesting approach to generating all the PNG exports at once! Your idea to implement looping for this purpose is quite intriguing, and the code you've implemented looks promising.

While we truly appreciate your effort and creativity, we need to consider the primary purpose of Peroxide_Gallery. Its main goal is to provide simple, accessible examples of how to use Peroxide. We're concerned that replacing the existing code with your more complex implementation might make it less approachable for newcomers to the library.

Given this, we don't think it would be appropriate to merge this PR as it stands. However, we definitely see value in your work and would like to include it in the gallery in a way that maintains the simplicity of the original examples while showcasing your advanced usage.

Here's what we propose:

1. Instead of modifying the existing code, could you create a new folder under the Plot directory? For example, "Plot/[New_Folder]".
2. Place your new code in this folder, demonstrating your approach to generating all styles at once.
3. Add a title and hyperlink for your new example under the **Plot** section in the README.md file.

If you make these changes and submit a new PR, we'd be happy to merge it. This way, we can maintain the simplicity of the original examples while also providing your more advanced implementation for users who are ready to explore further.

We truly appreciate your interest in contributing to Peroxide_Gallery. Your engagement with the project and willingness to experiment with new approaches is exactly the kind of community involvement we hope to foster. Thank you for your valuable input and for helping to make Peroxide more versatile and user-friendly!

**Comment by prismv** [comment]
Thank you for your valuable response.

Then I should create also issue report(s), because the goal ("demonstrating your approach to generating all styles at once") will actually not succeed as described shortly above.

**Comment by Axect** [comment]
Thank you for your follow-up message. I appreciate you bringing this to our attention, as it led to some important discoveries. I've taken the time to re-test the code based on your comments, and I've found some interesting results that I'd like to share with you.

You're absolutely correct - there is indeed an error when trying to render all styles simultaneously. Specifically, I've identified that the error occurs when IEEE and Nature styles are both activated. Interestingly, other combinations (such as Science, Default, and Nature; or Science, Default, and IEEE) work without issues.

This problem seems to stem from the current implementation of the Plot struct in Peroxide. The issue likely arises from the use of `plt.style.use(<STYLE>)` when adding styles. When multiple styles are applied in a single Rust program, it appears that these `plt.style.use` calls are conflicting with each other.

This is a crucial discovery, and I want to thank you for bringing it to our attention. We plan to address this in the next version of Peroxide. Our current thinking is to replace `plt.style.use` with `with plt.style.context():`, which should resolve the conflict.

Your finding is incredibly valuable for improving Peroxide. If you're interested in contributing further to this specific issue, I encourage you to create an issue in the Peroxide repository about this topic. I'll personally work on it from there.

Once we've resolved this issue, we'll be in a much better position to incorporate your new code into Peroxide_Gallery. Your approach to generating all styles at once will be much more effective and demonstrable after this fix.

Thank you again for your thorough testing and for bringing this to our attention. Your contributions are helping to make Peroxide more robust and versatile. We truly appreciate your engagement with the project!

**Comment by prismv** [comment]
Great!

I close this MR. It will be easier for me to create a new one.

**Pull request closed without merging**
